force-app/main/default/objects/priceOfFifty__c/priceOfFifty__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>priceOfFifty</label>
</CustomObject>

force-app/main/default/objects/priceOfFifty__c/fields/OldPriceTag__c.field-meta.xml
<CustomField>
    <fullName>OldPriceTag__c</fullName>
    <label>OldPriceTag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/priceOfFifty__c/fields/PriceTag__c.field-meta.xml
<CustomField>
    <fullName>PriceTag__c</fullName>
    <label>PriceTag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FiftyPriceFromCustomSettings.cls
public class FiftyPriceFromCustomSettings {
    @AuraEnabled (cacheable=true)
    public static List<Double> callToCS() {
        priceOfFifty__c cs = [SELECT Id, Name, PriceTag__c, OldPriceTag__c FROM priceOfFifty__c LIMIT 1];
        List<Double> result = new List<Double>();
        result.add(Math.round(cs.PriceTag__c));
        result.add(Math.round(cs.OldPriceTag__c));
        return result;
    }
}